version: 2
updates:
  # - package-ecosystem: pip
  #   directory: "/"
  #   schedule:
  #     interval: daily
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates once a month
      interval: 'monthly'
