codecov:
  require_ci_to_pass: no
  max_report_age: off

comment: false

ignore:
  - 'tests/*.py'
  - 'setup.py'

coverage:
  range: 25...75
  precision: 2
  round: down
  status:
    project:
      default:
        target: 50
        informational: true
    patch: off
    changes: off
